jwt:
  config:
    key: jwt     #签名密钥
    ttl: 3600000 #过期时间 1小时
qiniu:
  config:
    accessKey: PVT6BLWo5HANKtLi3iMstew0eLRP1ER3BJxr6PB9
    secretKey: Rx2moagdRbREcoY9D9EShxPzUMG8kfQGcmlYOS7i
    bucket: ihrm-bucket
    prefix: http://pvszbv17r.bkt.clouddn.com/